create test file and update proto
GTBitsOfGood/juno pull request #126
Opened 2024-10-22 05:24 UTC by zinichakraborty

I think there is missing implementation, but I will check with you guys in person on it tomorrow

2024-10-23 21:16 UTC, zinichakraborty commented
There will be compiling errors - will only be able to get back to them after Thursday

2024-11-02 23:12 UTC, tmthecoder requested changes
Make sure you run `yarn format:write` & `yarn lint` before pushing

2024-11-02 23:12 UTC, tmthecoder commented on packages/db-service/test/file_config.e2e-spec.ts
> +            buckets: FileServiceBucket[],
This should just be `[]`, no need for the `FileServiceBucket`

2024-11-02 23:12 UTC, tmthecoder commented on packages/proto/definitions/file_config.proto
> +  repeated file_bucket.Bucket buckets = 2;
The build failure is coming from here, this (and all the others) should be `config.Bucket`

2024-11-04 04:41 UTC, tmthecoder approved these changes
Made a few syntactic changes + controller/service issues that needed to be fixed

2024-11-04 04:41 UTC, merged