download file functionality
GTBitsOfGood/juno pull request #144
Opened 2024-11-10 12:49 UTC by Keerth1Keerthi

2024-11-10 17:37 UTC, tmthecoder requested changes

2024-11-10 17:37 UTC, tmthecoder commented on packages/file-service/src/modules/file/file.controller.ts
> +    await this.fileService.createFile(fileRequest);
We don't want to create a file to download, we want to make sure one exists (find/get)

2024-11-10 17:37 UTC, tmthecoder commented on packages/file-service/src/modules/file/file.controller.ts
> +    const bucketName = bucketJSON['name'];
Bucket shouldn't be a JSON field, it's better to split it into bucketName & configId in the proto

2024-11-10 17:37 UTC, tmthecoder commented on packages/file-service/src/modules/file/file.controller.ts
> +    const metadata = request.data;
Don't take request.data here, we don't need a `data` field in the Request, use the `provider` + `configId` to look up the provider in the DB service (CRUD methods from last sprint) and use the metadata field there to instantiate S3Client

2024-11-10 22:55 UTC, tmthecoder commented
@Keerth1Keerthi Take a look at Long's PR: (#143) to base your fixes off of

2024-11-12 01:11 UTC, tmthecoder requested changes
Make sure tests pass for all services

2024-11-12 01:11 UTC, tmthecoder commented on packages/file-service/src/modules/file_provider/file_provider.controller.ts
Why were these files deleted (and the test?)

2024-11-12 03:43 UTC, Keerth1Keerthi commented on packages/file-service/src/modules/file_provider/file_provider.controller.ts
I think when I merged main into my branch, I merged things really weirdly and the new files from main got deleted. I'll add them back!

2024-11-12 03:54 UTC, tmthecoder commented on packages/file-service/test/file.e2e-spec.ts
> +const TEST_SERVICE_ADDR = 'file-service:50003';
Tests may be failing because this is `50003` which is the same as the. upload tests, change this to `50004`

2024-11-12 04:56 UTC, merged